# Generated by Django 5.1.1 on 2024-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='lien',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
