# Generated by Django 5.1.1 on 2024-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_collection_remove_produit_image_remove_produit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduit',
            name='image',
            field=models.ImageField(upload_to='produits/images/'),
        ),
    ]
